### PR TITLE
fix: Drop Cargo.lock before renaming it

### PR DESCRIPTION
**Pull request by Marwes**
Lets it work on Windows

### CODE REVIEW

**Comment by sunng87** [comment]
Thanks! Is this to fix IOError on Windows?

**Comment by Marwes** [comment]
It fixes a IOError on windows at least since it is not possible to modify a file while it is being read from.

**Comment by sunng87** [comment]
Nice, thank you @Marwes

**Comment by sunng87** [comment]
Nice, thank you @Marwes

**Comment by sunng87** [comment]
Nice, thank you @Marwes

**Pull request merged**
