### PR TITLE
Moves configuration to release.toml

### LINKED ISSUE #52: Use subcommands for release levels
Before you hit **NO!** on your reviewer-keyboard, please let me explain 😉 

The Atom editor has a package management tool called `apm`. It was build for package management but it also helps you publishing atom packages. As it is explained in [here](https://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package) the tool has the following command structure:
```
$ apm publish <major | minor | patch>
```

I find this structure really compelling because it kinda *forces* you to use the tool for versioning and it keeps versioning in particular very organized. So I would like to see a simillar structure in this tool:

```
$ cargo publish <major | minor | patch>
```

### PR DESCRIPTION
**Pull request by sunng87**
Fixes #52, #47 

Configuration now stored in `$PROJECT/release.toml` or `$HOME/.release.toml`. `package.release.metadata` is still supported but deprecated.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Does this mean that support for `package.release.metadata` is going away eventually? I quite like it, it prevents polluting the project root with yet-another-config.

**Comment by sunng87** [comment]
Yes the section in Cargo.toml deprecated because I didn't see any other tools in the ecosystem using it like that. So I'm just to follow the community convention.

**Comment by jonas-schievink** [comment]
I'm not quite sure what you mean. The way cargo-release uses it doesn't seem to different to what [cargo-arch](https://github.com/wdv4758h/cargo-arch), docs.rs and [metadeps](https://github.com/joshtriplett/metadeps) use it for (except for text substitutions, maybe?). I feel like configuring the way a crate is published logically belongs into the manifest.

**Comment by sunng87** [comment]
@jonas-schievink OK. I will reconsider the choice between Cargo.toml and release.toml. Perhaps we can support both.

**Comment by jonas-schievink** [comment]
That would be great, thanks!

**Comment by autozimu** [comment]
I for one also don't like idea of migrating/creating separate file to store a few simple configs.

Please keep the support of `cargo.toml`, even if the docs will redirect new users to use separate files.

**Comment by lucab** [comment]
I'm also an happy user of the metadata section and would prefer not to have a separate file. Can I go ahead and send a PR to undeprecate it?

**Comment by sunng87** [comment]
@lucab please, thanks!

**Comment by lucab** [comment]
@sunng87 ack, it's up at https://github.com/sunng87/cargo-release/pull/71.

**Comment by sunng87** [comment]
@lucab thanks, merged

**Pull request merged**
