### PR TITLE
 docs: Split up docs 

### PR DESCRIPTION
**Pull request by epage**
The goal is to make it easier for people to find the documentation
relevant to their needs.

### CODE REVIEW

**Comment by epage** [comment]
See https://github.com/epage/cargo-release/tree/docs to explore what this is like.

**Comment by sunng87** [comment]
Perhaps we can also include the content of `reference.md` into `cargo release --help`

**Comment by epage** [comment]
I've been curious about the idea for a crate that would render markdown on the terminal.

**Comment by sunng87** [comment]
Markdown has excellent readability, it's ok to dump it directly I think

**Pull request merged**
