### PR TITLE
Upgrade crates-index->0.15

### PR DESCRIPTION
**Pull request by nickolay**
This updates git2-rs to 0.13, which [supports MacPorts users better](https://github.com/rust-lang/git2-rs/issues/180#issuecomment-678740147).

### CODE REVIEW

**Comment by nickolay** [comment]
We previously pinned rustc version to 1.37.0. This older compiler can't build the newer libraries, so I had to update travis.yml to the newest compiler

**Comment by sunng87** [comment]
Thanks 👍

**Comment by nickolay** [comment]
Wow, that was fast!

Any chance you could release a new version of cargo-release with this change? This would make `cargo install cargo-release` work for macports users out-of-box...

**Comment by sunng87** [comment]
@nickolay hello! This has benn released in 0.13.7

**Comment by nickolay** [comment]
Awesome, thank you!

**Pull request merged**
