### PR TITLE
Port to cargo_metadata where possible

### PR DESCRIPTION
**Pull request by epage**
For determining the default tag, I did not switch us from finding the git root to finding the workspace root.  I figured that if the crate wasn't in the git root, regardless of the use of workspaces, we probably want to scope the tag.

### CODE REVIEW

**Comment by epage** [comment]
1. `cargo metadata` doesn't expose `publish`, that is weird
2. `cargo_metadata` doesn't expose the `metadata` table.  I understand (its freeform, what API to provide?).

**Comment by epage** [comment]
nm, it does support metadata.  Somehow I missed that when going through the docs

https://docs.rs/cargo_metadata/0.7.1/cargo_metadata/struct.Package.html#structfield.metadata

**Comment by epage** [comment]
1. Did a rebase
2. Fixed an `expect` failing when run in a workspace root without a package (`pure_ws` test condition)

**Comment by sunng87** [comment]
Perhaps we can submit an issue for cargo_metadata to support `publish`?

Just knew about cargo_metadata is a great to for cargo ecosystem, I will close #63 because cargo_metadata is a better approach.

**Comment by epage** [comment]
> Perhaps we can submit an issue for cargo_metadata to support publish?

iirc `cargo metadata` (which `cargo_metadata` wraps) doesn't expose `publish`, so we'd first need the issue resolved in `cargo metadata`.

But yes, it'd be nice if they exposed it.

**Pull request merged**
